### ISSUE TITLE
SystemPack for Steam Gold Edition

### ISSUE THREAD

**Issue by KatekovAnton** [GothicFixTeam/GothicFix#2]
Hi. There are multiple archives for G2
```
G2Classic-SystemPack-1.8.exe
G2NoTR-SystemPack-1.8.exe
G2Odyssey-SystemPack-1.8.exe
G2Returning-SystemPack-1.8.exe
```
which of them should we use for stream gold edition version? Thank you!

**Comment by KuDeSnik33ra** [comment]
Hi, you need G2NoTR version. But 1.8 is outdated. Install v1.8 installer and unpack v1.9pre zip after it.

**Comment by KatekovAnton** [comment]
@KuDeSnik33ra thank you for your reply! I am but concerned 🤔 can you give me a link for 1.9? I can only see 1.8 release...

**Comment by KuDeSnik33ra** [comment]
https://github.com/GothicFixTeam/GothicFix/releases/tag/v1.9pre

**Comment by KuDeSnik33ra** [comment]
I have fixed bug, caused by bug in VisualStudio2017 FILE* io - Crash/infinite loop while loading save games. New pre here:
https://github.com/GothicFixTeam/GothicFix/releases/tag/v1.9pre2

**Comment by KatekovAnton** [comment]
Hi. Thank you. I was able to compile pre1 version but game still wont run correctly.

What I observed:
- I was not able to change screen resolution
- I saw new game videos
- Talking to Ksardas there was no main hero speeches
- After initial dialogue end - game crashes when started to move (I moved a bit and then it crashed)

Any Ideas?

**Comment by KuDeSnik33ra** [comment]
I wrote you in skype to get more info about the problem
